### ISSUE TITLE
Bouton Dark mode bugs

### ISSUE THREAD

**Issue by Anyr-Bagui** [eraflo/Inflow#119]
![image](https://user-images.githubusercontent.com/53833195/120514268-62e7c300-c3cd-11eb-8331-27d098c12536.png)

**Comment by Enzo-py** [comment]
Vous avez changer de place le darkmode ?

**Comment by Anyr-Bagui** [comment]
Script utilisant le bouton déplacé dans la page "parametres", là où se trouve le bouton
