### ISSUE TITLE
Boîtes commentaires passent en dessous de la page

### ISSUE THREAD

**Issue by Anyr-Bagui** [eraflo/Inflow#143]
N'affiche pas l'entièreté des boites commentaires en fonction de la taille de l'écran

100%
![image](https://user-images.githubusercontent.com/53833195/120792630-1b307b00-c536-11eb-834d-215b72e625fb.png)
90%
![image](https://user-images.githubusercontent.com/53833195/120792637-1ec40200-c536-11eb-908d-d4a3eb9c6f80.png)
125%
![image](https://user-images.githubusercontent.com/53833195/120792653-25527980-c536-11eb-8c64-610726c9d3af.png)

 (1920x1080)

**Comment by Enzo-py** [comment]
Je vais voir ca

>
