### ISSUE TITLE
PHP: programme qui créé des images webp

### ISSUE THREAD

**Issue by Anyr-Bagui** [eraflo/Inflow#145]
À chaque nouvelle image utilisateur pour l'avatar (et peut-être le fond ?) (sauf gifs), ce programme va compresser l'image en la convertissant en format webp

**Comment by Anyr-Bagui** [comment]
-https://developers.google.com/speed/webp/docs/cwebp

**Comment by timo-thi** [comment]
**Notes :**
using webptools library
`from webptools import cwebp` ...

Some usefull links :
https://pypi.org/project/webptools/
https://developers.google.com/speed/webp/docs/cwebp

**Comment by Anyr-Bagui** [comment]
Activer l'extension webp pour PHP
( ***php.ini** à mettre dans **X:\..\xampp\php\php.ini*** )
[activate_webp.zip](https://github.com/eraflo/Inflow/files/6784192/activate_webp.zip)

**Comment by Anyr-Bagui** [comment]
Il faut utiliser les images **webp** au lieu des images d'origines, sauf pour les gifs car ils n'ont pas l'air de fonctionner correctement

**Comment by Anyr-Bagui** [comment]
> Activer l'extension webp pour PHP
> ( _**php.ini** à mettre dans **X:..\xampp\php\php.ini**_ )
> [activate_webp.zip](https://github.com/eraflo/Inflow/files/6784266/activate_webp.zip)
> 
> Ou sinon
> 
> Activer l'extension en changeant la ligne dans le fichier **php.ini**
> `;extension=gd`
> en
> `extension=gd`

Ne sera plus nécessaire avec la librairie webp qui sera installée dans le répertoire principal (webpages/scripts)
