### ISSUE TITLE
Bug paramètre

### ISSUE THREAD

**Issue by Enzo-py** [eraflo/Inflow#146]
![image](https://user-images.githubusercontent.com/85191552/120834691-a96f2600-c563-11eb-83d2-8dd3cd67c95c.png)

Quand on clique sur Paramètre (en étant connecté) ca nous renvoie vers une page "Xampp" avec ce message d'erreur:
Warning: Undefined array key "font" in C:\xampp\htdocs\webPages\Parametres.php on line 19

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'inflow.police_ecriture' doesn't exist in C:\xampp\htdocs\webPages\Parametres.php:19 Stack trace: #0 C:\xampp\htdocs\webPages\Parametres.php(19): PDOStatement->execute(Array) #1 {main} thrown in C:\xampp\htdocs\webPages\Parametres.php on line 19

**Comment by Anyr-Bagui** [comment]
"Table 'inflow.police_ecriture' doesn't exist"
Importe la nouvelle base inflow dans #docs

1. supprime toutes les tables de la base
2. télécharge le fichier inflow_X.sql
3. sélectionne la base inflow
4. clique sur importer (en haut)
5. choisis ton fichier
6. clique sur executer en bas de la page

**Comment by Anyr-Bagui** [comment]
Tu n'es pas obligé d'assigner tout le monde pour ça xd

**Comment by Anyr-Bagui** [comment]
Si le problème est résolu, change le label en "resolved" et ferme l'issue
