### ISSUE TITLE
page article

### ISSUE THREAD

**Issue by eraflo** [eraflo/Inflow#231]
Et sur les articles c'est original d'tuiliser toute la largeur mais ça fais bcp trop condencer
typiquement les commentaire faudrait les mettre sous l'article et non à droite

**Comment by Anyr-Bagui** [comment]
Qu'est-ce que tu souhaite que je fasse exactement ?

**Comment by Anyr-Bagui** [comment]
@eraflo ??

**Comment by eraflo** [comment]
sur les articles, on enlève la division en colonne gauche milieu et droite et on passe l'article sur toute la largeur de la page.
Et les commentaires ainsi que les recommandations passent en-dessous de l'article.

**Comment by Anyr-Bagui** [comment]
@Enzo-py alors, c'est pas moi qui m'occupe de ça

**Comment by Enzo-py** [comment]
Alors... ça va être chiant.
Tu veux mettre les commentaires en bas des articles @eraflo
