### ISSUE TITLE
n'affiche pas d'erreur à l'utilisateur lorsqu'une image est trop grande

### ISSUE THREAD

**Issue by Anyr-Bagui** [eraflo/Inflow#31]
changement d'avatar avec une image trop volumineuse mène à rien : retour à la page profil et rien ne se passe (l'avatar n'est pas modifié et aucun message d'erreur n'apparait)

**Comment by eraflo** [comment]
normalement, message d'erreur est sensé s'affichait

**Comment by Anyr-Bagui** [comment]
tu as fait des tests ?

**Comment by eraflo** [comment]
Non, mais j'ai vérifier, ya m'a commandé qui regarde la taille du fichier et qui est sensé t'afficher un message d'erreur, après, j'ai remis un header sur la page édition profil au cas où. Mais j'ai pas encore commit, faut que tu fasses depuis la session que j'héberge

**Comment by Anyr-Bagui** [comment]
ah oui ok, donc le problème n'existe que sur la branche main
